# Generated by Django 3.2.22 on 2023-10-07 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='bug_report_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
